<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net11.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LabelDecisionApp.Console\sample-item-label-types.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <ProjectReference Include="..\LabelDecisionApp.Console\LabelDecisionApp.Console.csproj" />
    <ProjectReference Include="..\LabelDecisionApp.Integration\LabelDecisionApp.Integration.csproj" />
  </ItemGroup>

</Project>
